#!/bin/bash

cd   /alx-system_engineering-devops/0x02-shell_redirections

echo -e "#!/bin/bash\n echo "Hello, World\n"">0-hello_world

chmod u+x 0-hello_world

/alx-system_engineering-devops/auto_commit


